from base import *
"""
Django settings for money_converter project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1','dhan3531.pythonanywhere.com']
